<a href="https://colab.research.google.com/github/Ragav5108/Datascience_internship/blob/main/Numpy_arraycreation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#array
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
#zeros array
z = np.zeros((2, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones array
o = np.ones((3, 2))
print(o)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#fill with constant
f = np.full((2, 2), 9)
print(f)

[[9 9]
 [9 9]]


In [ ]:

#identity matrix
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#uninitialized array
emp = np.empty((2, 2))
print(emp)

[[2.89096416e-315 0.00000000e+000]
 [1.58101007e-322 2.84532800e-234]]


In [ ]:
#array with range
r = np.arange(0, 10, 2)
print(r)

[0 2 4 6 8]


In [ ]:
#evenly spaced value
l = np.linspace(0, 5, 5)
print(l)

[0.   1.25 2.5  3.75 5.  ]


In [ ]:

#random float valve
rand_f = np.random.rand(2, 2)
print(rand_f)

[[0.15773779 0.25483914]
 [0.90457725 0.068966  ]]


In [ ]:
#random integer
rand_i = np.random.randint(1, 10, (2, 3))
print(rand_i)

[[1 3 2]
 [9 9 9]]
