<a href="https://colab.research.google.com/github/Ragav5108/Datascience_internship/blob/main/Numpy_arraymanipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#reshape
#Change the shape of an array.

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((2, 3))  # Convert 1D to 2D (2 rows, 3 columns)
print(b)

[[1 2 3]
 [4 5 6]]


In [2]:

#reshape using range
import numpy as np

# Create an array with values from 0 to 11 (12 values)
a = np.arange(12)

# Reshape it to 3 rows and 4 columns
b = a.reshape((3, 4))

print("Original 1D array:\n", a)
print("Reshaped 2D array (3x4):\n", b)

Original 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 2D array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
#flatten
# Convert multi-dimensional array to 1D.

a = np.array([[1, 2], [3, 4]])
b = a.flatten()
print(b)

[1 2 3 4]


In [5]:
#transpose
#Swap rows and columns.
a = np.array([[1, 2], [3, 4]])
b = a.T
print(b)

[[1 3]
 [2 4]]


In [11]:
#Stacking Arrays (Vertical & Horizontal)

a = np.array([1, 2])
b = np.array([3, 4])

print('Vertical Stack')
v = np.vstack((a, b))
print(v)

print(' Horizontal Stack ')
h = np.hstack((a, b))
print(h)

Vertical Stack
[[1 2]
 [3 4]]
 Horizontal Stack 
[1 2 3 4]


In [12]:
#Splitting Arrays

a = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 parts
split = np.array_split(a, 3)
print(split)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
#Joining Arrays

a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))
print(c)

[1 2 3 4]


In [14]:
#Insert Elements

a = np.array([1, 2, 4])
b = np.insert(a, 2, 3)  # Insert 3 at index 2
print(b)

[1 2 3 4]


In [15]:
#Delete Elements

a = np.array([1, 2, 3, 4])
b = np.delete(a, 2)  # Remove element at index 2
print(b)

[1 2 4]


In [16]:
#Repeat Elements

a = np.array([1, 2])
b = np.repeat(a, 3)  # Repeat each element 3 times
print(b)

[1 1 1 2 2 2]


In [17]:
#Tile Array (Repeat Whole Array)

a = np.array([1, 2])
b = np.tile(a, 3)  # Repeat array 3 times
print(b)

[1 2 1 2 1 2]
